version: '3.8'

services:
  app:
    build:
      context: .
    container_name: my-app
    depends_on:
      - db
    ports:
      - "3000:3000"
    environment:
      RAILS_ENV: production
      DATABASE_URL: "postgresql://${POSTGRES_USER}:${POSTGRES_PASSWORD}@db:5432/${POSTGRES_DB}"
      RAILS_MASTER_KEY: "${RAILS_MASTER_KEY}" # Load master key from .env file
    volumes:
      - .:/rails
    command: ./bin/rails server -b 0.0.0.0 -p 3000

  db:
    image: postgres:15
    container_name: postgres-db
    environment:
      POSTGRES_USER: "${POSTGRES_USER}"
      POSTGRES_PASSWORD: "${POSTGRES_PASSWORD}"
      POSTGRES_DB: "${POSTGRES_DB}"
    ports:
      - "5432:5432"
    volumes:
      - postgres-data:/var/lib/postgresql/data

volumes:
  postgres-data:
